import { assertIsolatedDatabaseTarget } from '../../../scripts/db/isolated-database-target.mjs';
import assert from 'node:assert/strict';
import { before,beforeEach,after,test } from 'node:test';
import { drizzle } from 'drizzle-orm/node-postgres';
import { sql } from 'drizzle-orm';
import pg from 'pg';
import { revokeApplicationSession } from '../../../src/modules/identity/application/session-revocation-service.js';
import { issueApplicationSession,authenticateApplicationSession } from '../../../src/modules/identity/application/session-service.js';
import { PostgresSessionCommandTransaction,type SessionTransactionBindings } from '../../../src/modules/identity/infrastructure/persistence/postgres-session-command-transaction.js';
import { PostgresIdentityRepository } from '../../../src/modules/identity/infrastructure/persistence/postgres-identity-repository.js';
import { PostgresApplicationSessionRepository } from '../../../src/modules/identity/infrastructure/persistence/postgres-application-session-repository.js';
import { IdentityCommandDependenciesUnavailableError } from '../../../src/modules/identity/application/ports/identity-command-transaction.js';
import { ApplicationSessionNotFoundError } from '../../../src/modules/identity/application/ports/application-session-repository.js';
import * as schema from '../../../src/modules/identity/infrastructure/persistence/schema.js';
const connectionString=assertIsolatedDatabaseTarget(process.env.DATABASE_URL);
const pool=new pg.Pool({connectionString,statement_timeout:5000}),db=drizzle(pool,{schema});
const identities=new PostgresIdentityRepository(db),sessions=new PostgresApplicationSessionRepository(db);
const now=new Date('2026-10-05T03:00:00Z');let credential='';
const request=()=>({actorReference:'fixture',actorClass:'HumanActor' as const,targetIdentityId:'identity-1',targetSessionId:'one',requestId:'request-1',now:new Date(now)});
// Disposable transaction evidence probe; no admitted AuditEvent storage or C14 adapter.
before(async()=>{await pool.query('create schema test_session_probe');await pool.query('create table test_session_probe.audit(session_id text,request_id text,transaction_id bigint,backend_pid int)');});
beforeEach(async()=>{await pool.query('truncate identity_identities cascade');await pool.query('truncate test_session_probe.audit');for(const id of ['identity-1','identity-2'])await identities.create({id,now});for(const id of ['one','two','other']){const issued=await issueApplicationSession(sessions,{id,identityId:id==='other'?'identity-2':'identity-1',now});if(id==='one')credential=issued.credential;}});
after(async()=>{await pool.query('drop schema if exists test_session_probe cascade');await pool.end();});
function bindings(options:{deny?:boolean;beforeAppend?:boolean;afterAppend?:boolean}={}):SessionTransactionBindings{return {
 authorization:tx=>({async requireSessionAuthorization(input){if(options.deny)throw new Error('fixture denied');await tx.execute(sql`select id from identity_identities where id=${input.targetIdentityId} for update`);}}),
 audit:tx=>({async appendRequired(facts){if(options.beforeAppend)throw new Error('fixture audit unavailable');assert.equal(facts.action,'RevokeApplicationSession');if(facts.action!=='RevokeApplicationSession')throw new Error('unexpected audit action');const state=await tx.execute(sql`select status from identity_application_sessions where id=${facts.targetSessionId}`);assert.equal(state.rows[0]?.status,'REVOKED');await tx.execute(sql`insert into test_session_probe.audit values (${facts.targetSessionId},${facts.requestId},txid_current(),pg_backend_pid())`);if(options.afterAppend)throw new Error('fixture append failed');}}),
};}
async function state(){return {sessions:(await pool.query('select id,status from identity_application_sessions order by id')).rows,audits:(await pool.query('select * from test_session_probe.audit')).rows};}
test('missing session backend bindings refuse execution without effects',async()=>{await assert.rejects(revokeApplicationSession(new PostgresSessionCommandTransaction(db),request()),IdentityCommandDependenciesUnavailableError);const s=await state();assert.ok(s.sessions.every(x=>x.status==='ACTIVE'));assert.equal(s.audits.length,0);});
test('denied session authorization cannot mutate or append',async()=>{await assert.rejects(revokeApplicationSession(new PostgresSessionCommandTransaction(db,bindings({deny:true})),request()),/denied/);const s=await state();assert.ok(s.sessions.every(x=>x.status==='ACTIVE'));assert.equal(s.audits.length,0);});
test('scoped revocation commits exactly its session and required probe append; credential replay denies',async()=>{const result=await revokeApplicationSession(new PostgresSessionCommandTransaction(db,bindings()),request());assert.equal(result.status,'REVOKED');const s=await state();assert.deepEqual(s.sessions,[{id:'one',status:'REVOKED'},{id:'other',status:'ACTIVE'},{id:'two',status:'ACTIVE'}]);assert.equal(s.audits.length,1);assert.equal(await authenticateApplicationSession(sessions,credential,now),null);});
for(const option of ['beforeAppend','afterAppend'] as const)test(`${option} failure rolls back revocation and audit probe`,async()=>{await assert.rejects(revokeApplicationSession(new PostgresSessionCommandTransaction(db,bindings({[option]:true})),request()),/fixture/);const s=await state();assert.ok(s.sessions.every(x=>x.status==='ACTIVE'));assert.equal(s.audits.length,0);assert.ok(await authenticateApplicationSession(sessions,credential,now));});
for(const input of [{targetIdentityId:'identity-2'},{targetSessionId:'missing'}])test(`wrong or absent owner session fails without disclosed data or writes: ${JSON.stringify(input)}`,async()=>{await assert.rejects(revokeApplicationSession(new PostgresSessionCommandTransaction(db,bindings()),{...request(),...input}),ApplicationSessionNotFoundError);const s=await state();assert.ok(s.sessions.every(x=>x.status==='ACTIVE'));assert.equal(s.audits.length,0);});
test('16 concurrent revocations produce one transition and one probe audit; retries stay terminal',async()=>{const transaction=new PostgresSessionCommandTransaction(db,bindings());const results=await Promise.all(Array.from({length:16},(_,i)=>revokeApplicationSession(transaction,{...request(),requestId:`concurrent-${i}`})));assert.ok(results.every(x=>x.status==='REVOKED'));await revokeApplicationSession(transaction,{...request(),requestId:'retry'});assert.equal((await state()).audits.length,1);});
test('expired sessions cannot transition to REVOKED or append success audit',async()=>{await pool.query("update identity_application_sessions set status='EXPIRED',expired_at=$1 where id='one'",[now]);const result=await revokeApplicationSession(new PostgresSessionCommandTransaction(db,bindings()),request());assert.equal(result.status,'EXPIRED');assert.equal((await state()).audits.length,0);});
test('session authorization, owner writes and append use the same PostgreSQL transaction/connection',async()=>{let observed:{transaction_id:unknown;backend_pid:unknown}|undefined;const b=bindings();const transaction=new PostgresSessionCommandTransaction(db,{authorization:tx=>({async requireSessionAuthorization(input){const result=await tx.execute(sql`select txid_current() as transaction_id,pg_backend_pid() as backend_pid`);observed={transaction_id:result.rows[0]?.transaction_id,backend_pid:result.rows[0]?.backend_pid};await b.authorization(tx).requireSessionAuthorization(input);}}),audit:b.audit});await revokeApplicationSession(transaction,request());const rows=(await state()).audits;assert.ok(observed);assert.equal(String(rows[0].transaction_id),String(observed.transaction_id));assert.equal(rows[0].backend_pid,observed.backend_pid);});
