import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildWorkflowReport, closeWorkflowReport, planWorkflowRecovery, reportDigest } from '../verification/workflow-lifecycle.mjs';
import { deriveWorkflowInventory } from '../verification/workflow-lifecycle-inventory.mjs';
import { inspectWorkflowLifecycles } from '../verification/validate-workflow-lifecycle.mjs';
const root = new URL('../..', import.meta.url).pathname;
const definition={required_steps:['checkout','verify'],job_id:'audit',workflow_path:'.github/workflows/audit.yml',workflow_sha256:'a'.repeat(64)};
const input={definition,context:{expected_sha:'b'.repeat(40),run_id:1,attempt:1,job_id:'audit',event:'push'},source:{source_sha:'b'.repeat(40),tree_sha:'c'.repeat(40),dirty:false},steps:{checkout:{outcome:'success',conclusion:'success'},verify:{outcome:'success',conclusion:'success'}},jobStatus:'success'};
function checkpoint(){return buildWorkflowReport(structuredClone(input));}
function receipt(report){return {run_id:1,attempt:1,job_id:'audit',workflow_path:definition.workflow_path,workflow_sha256:definition.workflow_sha256,source_sha:input.source.source_sha,tree_sha:input.source.tree_sha,artifact_id:2,artifact_sha256:'d'.repeat(64),archive_sha256:'d'.repeat(64),artifact_report_sha256:report.report_sha256,artifact_expired:false,upload_outcome:'success',run_conclusion:'success',artifact_name:'workflow-lifecycle-1-1-audit'};}
test('successful execution awaits external retention receipt',()=>{const report=checkpoint();assert.equal(report.state,'AWAITING_RECEIPT');assert.equal(report.closure,'OPEN');assert.equal(report.handoff_authorized,false);});
test('matching external receipt closes development evidence only',()=>{const report=checkpoint();const result=closeWorkflowReport(report,receipt(report));assert.equal(result.state,'CLOSED');assert.equal(result.runtime_activation,'BLOCKED');assert.equal(result.shared_or_production_execution_authorized,false);});
for(const [field,value] of Object.entries({run_id:3,attempt:2,job_id:'other',workflow_path:'other',workflow_sha256:'e'.repeat(64),source_sha:'e'.repeat(40),tree_sha:'e'.repeat(40),artifact_id:0,artifact_sha256:'e'.repeat(64),archive_sha256:'e'.repeat(64),artifact_report_sha256:'e'.repeat(64),artifact_expired:true,upload_outcome:'failure',run_conclusion:'failure',artifact_name:'wrong'}))test(`receipt rejects ${field}`,()=>{const report=checkpoint();assert.equal(closeWorkflowReport(report,{...receipt(report),[field]:value}).state,'BLOCKED');});
for(const [outcome,conclusion,state] of [['failure','success','FAILED'],['cancelled','cancelled','INTERRUPTED'],['skipped','skipped','BLOCKED'],['success','failure','CONTRADICTORY']])test(`step ${outcome}/${conclusion} stays ${state}`,()=>{const altered=structuredClone(input);altered.steps.verify={outcome,conclusion};assert.equal(buildWorkflowReport(altered).state,state);});
test('missing step blocks',()=>{const altered=structuredClone(input);delete altered.steps.verify;assert.equal(buildWorkflowReport(altered).state,'BLOCKED');});
test('dirty and wrong source block',()=>{for(const source of [{...input.source,dirty:true},{...input.source,source_sha:'e'.repeat(40)}])assert.equal(buildWorkflowReport({...input,source}).state,'BLOCKED');});
test('tampered report rejected',()=>{const report=checkpoint();assert.equal(closeWorkflowReport({...report,created_at:'changed'},receipt(report)).state,'BLOCKED');});
test('even rehashed runtime authority escalation rejected',()=>{const report={...checkpoint(),runtime_activation:'ACTIVE'};report.report_sha256=reportDigest(report);assert.equal(closeWorkflowReport(report,receipt(report)).state,'BLOCKED');});
test('failed read-only attempt needs diagnosis and new attempt',()=>{const report=buildWorkflowReport({...input,jobStatus:'failure'});assert.equal(planWorkflowRecovery(report).state,'BLOCKED');const next=planWorkflowRecovery(report,{effect:'READ_ONLY_DEVELOPMENT_VERIFICATION',diagnosis:'test failure'});assert.equal(next.state,'NEW_ATTEMPT_REQUIRED');assert.equal(next.preserve_prior_evidence,true);});
test('external side effects never gain automatic retry authority',()=>{const report=buildWorkflowReport({...input,jobStatus:'failure'});for(const canonical_readback of ['UNKNOWN','PROVEN'])assert.equal(planWorkflowRecovery(report,{effect:'EXTERNAL_WRITE',diagnosis:'lost response',canonical_readback}).state,'BLOCKED');});
test('all CI and product workflows inventoried without product closure claims',()=>{const inventory=deriveWorkflowInventory(root);assert.equal(inventory.product.length,23);assert.ok(inventory.ci.length>=44);assert.ok(inventory.product.every(row=>row.closure==='BLOCKED'));assert.deepEqual(inspectWorkflowLifecycles(root),[]);});
