import test from 'node:test';
import assert from 'node:assert/strict';
import {cpSync,mkdtempSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {validateDecisionClosure,PKG} from '../verification/validate-decision-closure.mjs';
const root=resolve(new URL('../..',import.meta.url).pathname);
const edit=(dir,path,fn)=>writeFileSync(join(dir,path),fn(readFileSync(join(dir,path),'utf8')));
const json=(dir,path,fn)=>edit(dir,path,text=>{const value=JSON.parse(text);fn(value);return JSON.stringify(value,null,2)+'\n';});
const registration=(dir,fn)=>json(dir,'governance/decision-closure/registration.json',fn);
function rejects(name,mutate,pattern){test(name,()=>{const dir=mkdtempSync(join(tmpdir(),'teach-closure-'));try{for(const path of ['contracts','governance','kernel'])cpSync(join(root,path),join(dir,path),{recursive:true});mutate(dir);const r=validateDecisionClosure(dir);assert.ok(r.errors.some(x=>pattern.test(x)),`expected ${pattern}; got ${r.errors.join('\n')}`);}finally{rmSync(dir,{recursive:true,force:true});}});}
test('complete registered policy has exact approval, versions, IDs and residuals',()=>assert.deepEqual(validateDecisionClosure(root).errors,[]));
rejects('different manifest approval fails',d=>registration(d,x=>{x.approved_manifest_sha256='0'.repeat(64);}),/owner approval provenance/);
rejects('owner identity cannot be invented',d=>registration(d,x=>{x.owner='DevelopmentAgent';}),/owner approval provenance/);
rejects('partial or reordered batches fail',d=>registration(d,x=>{x.batches=[2,1,3,4,5,6];}),/ordered batches/);
rejects('missing contract revision fails',d=>registration(d,x=>{x.contracts.pop();}),/twenty-contract/);
rejects('runtime authority cannot be granted',d=>registration(d,x=>{x.runtime_activation_authorized=true;}),/cannot grant runtime/);
rejects('production authority cannot be granted',d=>registration(d,x=>{x.shared_or_production_execution_authorized=true;}),/cannot grant runtime/);
rejects('self-review cannot become independent proof',d=>registration(d,x=>{x.independent_verification='PROVEN';}),/cannot grant runtime/);
rejects('unknown runtime evidence cannot become proven',d=>registration(d,x=>{x.implementation_conformance='PROVEN';}),/cannot grant runtime/);
rejects('approved packet tampering fails',d=>edit(d,`${PKG}/04-session-transport-security-spec.md`,x=>x.replace('SameSite=Lax','SameSite=None')),/approved artifact digest/);
rejects('missing approved artifact fails closed',d=>rmSync(join(d,`${PKG}/c14-capability-matrix.json`)),/approved artifact missing/);
rejects('registered CSRF semantics cannot weaken',d=>edit(d,'governance/decision-closure/04-session-transport-security-spec.md',x=>x.replace('No `Referer` fallback','Use `Referer` fallback')),/normative specification changed/);
rejects('registered matrix cannot import a legacy grant',d=>edit(d,'governance/decision-closure/c14-capability-matrix.json',x=>x+'\n'),/registered matrix differs/);
rejects('resolved question cannot re-open',d=>edit(d,'contracts/c12-application-sessions-contract.md',x=>x.replace('**Resolved.** Owner, 2026-10-05: The session cookie MUST','**Open.** Owner, 2026-10-05: The session cookie MUST')),/nine residual|resolution missing/);
rejects('CERT-2 cannot be silently resolved',d=>edit(d,'contracts/c34-certification-credentials-contract.md',x=>x.replace('Who approves certification criteria versions','Resolved. Who approves certification criteria versions')),/nine residual|sole explicit blocker/);
rejects('residual export deadline cannot be invented',d=>edit(d,'contracts/c15-data-isolation-privacy-contract.md',x=>x.replace('What export fulfillment deadline applies?','Export must complete in 30 days.')),/residual fabricated or lost/);
rejects('current normative cookie policy must carry its value',d=>edit(d,'contracts/c12-application-sessions-contract.md',x=>x.replace('- **SES-5** — The session cookie MUST set `SameSite=Lax`','- **SES-5** — The session cookie MUST set `SameSite=None`')),/normative value missing/);
rejects('unrelated audit immutability cannot weaken',d=>edit(d,'contracts/c23-audit-lifecycle-events-contract.md',x=>x.replace('MUST NOT be updated or deleted through application paths','MAY be deleted through application paths')),/unrelated requirement changed/);
rejects('renumbered requirement fails',d=>edit(d,'contracts/c15-data-isolation-privacy-contract.md',x=>x.replace('**PRIV-1**','**PRIV-99**')),/IDs changed/);
rejects('renumbered acceptance case fails',d=>edit(d,'contracts/c12-application-sessions-contract.md',x=>x.replace('SES-AC-1 ','SES-AC-99 ')),/IDs changed/);
rejects('historical body cannot be rewritten',d=>edit(d,'contracts/superseded/c12-application-sessions-contract-1.1.0.md',x=>x.replace('**SES-1**','**SES-99**')),/historical body changed/);
rejects('archive cannot remain active',d=>edit(d,'contracts/superseded/c00-system-authority-contract-1.0.3.md',x=>x.replace('"status": "superseded"','"status": "active"')),/C00 template/);
rejects('missing approval ledger fails',d=>edit(d,'contracts/APPROVAL-RECORD.md',x=>x.replace('## Part 25 — Decision-closure r3.1 registration (#75)','## Lost registration')),/approval ledger/);
rejects('unapproved version fails',d=>edit(d,'contracts/c12-application-sessions-contract.md',x=>x.replace('"version": "1.2.0"','"version": "1.3.0"')),/approved current version/);
rejects('capability promotion cannot ride with registration',d=>json(d,'kernel/capabilities.json',x=>{x.entries.push({id:'identity.credential.authenticate',status:'approved'});}),/capability promotion remains separate/);
